[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
hook_add = '''
    " .入力時に補完候補を表示しない
    let g:jedi#popup_on_dot = 0
    " 勝手に最初の候補を入力しない
    let g:jedi#popup_select_first = 0
    " docstringは表示しない
    "autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'vim-scripts/FuzzyFinder'

[[plugins]]
repo = 'vim-scripts/L9'

[[plugins]]
repo = 'vim-scripts/taglist.vim'

[[plugins]]
repo = 'vim-scripts/SQLUtilities'

[[plugins]]
repo = 'kevinw/pyflakes-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'osyo-manga/vim-brightest'

[[plugins]]
repo = 'thinca/vim-fontzoom'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
