#!/bin/bash

# Required on kitty session
# and set preference : Terminal > Remote-controlled > Windows clipboard 

# TODO
# add executable permission to this file

line=`cat`

if [ -z "$TMUX" ]; then
  echo -ne '\e''[5i'
  echo "$line"
  echo -ne '\e''[4i'
else
  # https://github.com/tmux/tmux/issues/636#issuecomment-264976452
  echo -ne "\033Ptmux;\033\033[5i$line\033\033[4i\033\\"
fi

echo "$line"
